version: '3.7'

services:
  recipe-app:
    container_name: recipe-app
    build:
      context: .
      args:
        NODE_ENV: $NODE_ENV
    environment:
      PORT: $PORT
      PG_USER: $PG_USER
      PG_HOST: $PG_HOST
      PG_DATABASE: $PG_DATABASE
      PG_PASSWORD: $PG_PASSWORD
      PG_PORT: $PG_PORT
      LOGGER_LEVEL: $LOGGER_LEVEL
